# Deploy dotfiles only, needs git etc.
---
- name: Nvim only
  hosts: all
  tasks:
    - include_role:
        name: "personalization"
      vars:
        ansible_ssh_user: "puttehi"
        personalization_user: "puttehi"
        personalization_install_nvim: true
