# Deploy stack of services
# Assumes Nginx is already installed with certs using roles/deployment/nginx (see play-nginx.yml)
---
- name: "Deploy stack"
  hosts: all
  handlers:
    - name: "Nginx handler: Reload configuration"
      ansible.builtin.service:
        name: "nginx"
        state: reloaded
  tasks:
    - name: "Nginx: Template Nginx config for the stack"
      ansible.builtin.template:
        src: "default.conf.j2"
        dest: "/etc/nginx/conf.d/default.conf"
        owner: "root"
        group: "root"
        mode: u=rwx,g=r,o=r
        force: true # Change if contents changes even if file already exists
      vars:
        nginx_domain: "vps.puttehi.eu"
        # vps.puttehi.eu/* (Vouch layer)
        nginx_reverse_proxy:
          "/":
            dest: "http://localhost:8080"
          "/hello":
            dest: "http://localhost:8081"
          "~ ^/v1/database":
            dest: "http://localhost:9001" # SpacetimeDB
            # Websocket support + STDB recommendations + publish requires nginx body size hack
            config: |
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header Host $host;
        # www.puttehi.eu/* (Open to public)
        nginx_reverse_proxy_public:
          "/":
            dest: "http://localhost:9000" # Website
          # SpacetimeDB public endpoints
          "~ ^/v1/database/[^/]+/(subscribe|call/[^/]+|schema)$":
            dest: "http://localhost:9001"
            # Websocket support + STDB recommendations
            config: |
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header Host $host;
          "/v1/ping":
            dest: "http://localhost:9001" # Just HTTP, no need for config
          "/phaserclient":
            dest: "http://localhost:9002" # spacetime-phaser-client
            # Just in case?
            config: |
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header Host $host;
        nginx_cert_path: "/etc/letsencrypt/live"
      notify: "Nginx handler: Reload configuration"

    - name: "Vouch: Create config dir"
      ansible.builtin.file:
        path: "/root/config"
        state: directory
        mode: u=rwx,g=rx,o=rx
        owner: "root"
        group: "root"

    - name: "Vouch: Template config.yml"
      ansible.builtin.template:
        src: "config.yml.j2"
        dest: "/root/config/config.yml"
        mode: u=rwx,g=,o=
        owner: "root"
        group: "root"
        force: true
      vars:
        github_client_id: "{{ lookup('file', '~/.ssh/vps/github_client_id') }}"
        github_client_secret: "{{ lookup('file', '~/.ssh/vps/github_client_secret') }}"

    - name: "Podman: root / vouch-proxy"
      include_role:
        name: "deployment/podman"
      vars:
        podman_user: "root"
        podman_containers:
          - name: "vouch-proxy"
            image: "quay.io/vouch/vouch-proxy"
            detach: true
            ports:
              - "127.0.0.1:9090:9090"
            volumes:
              - "/root/config:/config"

    - name: "Podman: puttehi / httpd, hello-world, htmx-go-portfolio"
      include_role:
        name: "deployment/podman"
      vars:
        podman_user: "puttehi"
        podman_containers:
          - name: "httpd"
            image: "docker.io/library/httpd"
            state: started
            ports:
              - "127.0.0.1:8080:80/tcp"
            detach: true
            tty: true
            log_opt:
              max_size: "10mb"
          - name: "hello-world"
            image: "docker.io/strm/helloworld-http"
            state: started
            ports:
              - "127.0.0.1:8081:80/tcp"
            detach: true
            tty: true
            log_opt:
              max_size: "10mb"
          - name: "htmx-go-portfolio"
            image: "ghcr.io/puttehi/htmx-go-portfolio:2cf74ce6328b818956dc99c0001997ec93a22077"
            login_config:
              # Remember to allow repository in GitHub Packages to be able to login and pull
              login_registry: ghcr.io
              login_user: "{{ lookup('ansible.builtin.env', 'PODMAN_USER') }}" # github.actor
              login_password: "{{ lookup('ansible.builtin.env', 'PODMAN_PASSWORD') }}" # github.token
            state: started
            ports:
              - "127.0.0.1:9000:3000/tcp"
            detach: true
            tty: true
            log_opt:
              max_size: "100mb"
          - name: "spacetimedb"
            user: "root" # TODO: Update podman and :U the mounts so the default user works (STDB silently hangs on no permissions)
            state: started
            image: "docker.io/clockworklabs/spacetime:v1.1.0"
            command: "start" # --listen-addr='0.0.0.0:3000' is default, help text wrongly states 80 and 127.0.0.1:3000 does not work in 1.1.0, or Podman, or Docker, so it has been omitted (not necessary for container anyways)
            ports:
              - "127.0.0.1:9001:3000" # Public traffic
            volume:
              # Assumes directories exist.
              #- "...:/app"
              #- "...:/opt/spacetime"
              #- "...:/usr/bin/spacetime"
              - "/home/puttehi/stdb/home/spacetime/.local/share/spacetime:/root/.local/share/spacetime"
              - "/home/puttehi/stdb/home/spacetime/.config/spacetime:/root/.config/spacetime"
            detach: true
            tty: true
            log_opt:
              max_size: "100mb"
          - name: "spacetime-phaser-client"
            image: "ghcr.io/puttehi/spacetime-phaser-client:d8008381b084141315c768f75cfc48b3fec68dad"
            login_config:
              # Remember to allow repository in GitHub Packages to be able to login and pull
              login_registry: ghcr.io
              login_user: "{{ lookup('ansible.builtin.env', 'PODMAN_USER') }}" # github.actor
              login_password: "{{ lookup('ansible.builtin.env', 'PODMAN_PASSWORD') }}" # github.token
            state: started
            ports:
              - "127.0.0.1:9002:80/tcp"
            detach: true
            tty: true
            log_opt:
              max_size: "100mb"

