---
- name: Install package
  ansible.builtin.package:
    name:
      - ripgrep
      - fd-find
      - bat
      - fzf
      - tldr
    state: latest

- name: Template package-related dotfile
  ansible.builtin.template:
    src: ".{{ item }}rc.j2"
    dest: "/home/{{ outer_item }}/.{{ item }}rc"
    owner: "{{ outer_item }}"
    group: "{{ outer_item }}"
  loop:
      - ripgrep
      - fd-find
      - bat
      - fzf
      - tldr

- name: Enable package-related dotfile
  ansible.builtin.lineinfile:
    line: "source /home/{{ outer_item }}/.{{ item }}rc"
    path: "/home/{{ outer_item }}/.bashrc"
  loop:
      - ripgrep
      - fd-find
      - bat
      - fzf
      - tldr
