---
- name: "Deploy container {{ outer_item.image }}"
  become: true
  become_user: "{{ podman_user }}"
  remote_user: "{{ podman_user }}"
  block:
    - name: "Deploy container: Login to registry"
      containers.podman.podman_login:
        username: "{{ outer_item.login_user }}"
        password: "{{ outer_item.login_password }}"
        registry: "{{ outer_item.login_registry }}"
      when:
        - outer_item.login_config is defined
    - name: "Deploy container: Pull container image"
      containers.podman.podman_image:
        name: "{{ outer_item.image }}"
    - name: "Deploy container: Set container configuration"
      # login_config is invalid for podman_container, let's drop it
      # https://stackoverflow.com/a/74475354
      containers.podman.podman_container: "{{ outer_item | combine({ 'login_config': omit }) }}"
