---
- name: "Deploy container {{ outer_item.image }}"
  become: true
  become_user: "{{ podman_user }}"
  remote_user: "{{ podman_user }}"
  block:
    - name: "Deploy container: Pull container image"
      containers.podman.podman_image:
        name: "{{ outer_item.image }}"
    - name: "Deploy container: Set container configuration"
      containers.podman.podman_container: "{{ outer_item }}"

