---
- name: Remove root password login
  ansible.builtin.user:
    user: "root"
    password: "*"

- name: Make initial users
  ansible.builtin.user:
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    state: present
    shell: "{{ item.value.shell }}"
  loop: "{{ base_users | dict2items }}"

- name: Assign initial users to groups
  ansible.builtin.user:
    name: "{{ item.key }}"
    state: present
    groups: "{{ item.key }},{{ item.value.groups }}" # Declarative
  loop: "{{ base_users | dict2items }}"

- name: Make desired initial users sudoers
  community.general.sudoers:
    name: "{{ item.key }}"
    user: "{{ item.key }}"
    commands: ALL
    state: present
  loop: "{{ base_users | dict2items }}"
  when: "{{ (item.value.sudoer | bool) == true }}"

- name: Set authorized_keys for initial users
  include_tasks: inner_authorized_key.yml
  loop: "{{ base_users | dict2items }}"
  loop_control:
    loop_var: outer_item

- name: Update package manager cache
  include_tasks: package_update.yml

- name: Upgrade installed packages
  include_tasks: package_upgrade.yml

